apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app2
  namespace: default
spec:
  selector:
    app: spring-boot-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
